export const FETCH_ADD_OFFERS_SUCCESS = 'FETCH_ADD_OFFERS_SUCCESS'
export const FETCH_GET_ALL_OFFERS_REQUEST = "FETCH_GET_ALL_OFFERS_REQUEST";
export const FETCH_GET_ALL_OFFERS_SUCCESS = "FETCH_GET_ALL_OFFERS_SUCCESS";   
export const FETCH_GET_ALL_OFFERS_FAILURE = "FETCH_GET_ALL_OFFERS_FAILURE";